# Generated by Django 5.1.7 on 2025-03-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0003_invitation_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='collaborator',
            new_name='collaborator_email',
        ),
    ]
