# Generated by Django 5.1.7 on 2025-04-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0004_rename_collaborator_invitation_collaborator_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='permission',
            field=models.CharField(choices=[('READ', 'read'), ('WRITE', 'write')], default='write', max_length=8),
        ),
    ]
