# Generated by Django 5.1.7 on 2025-04-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0005_collaboration_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='permission',
        ),
        migrations.AddField(
            model_name='invitation',
            name='permission',
            field=models.CharField(choices=[('READ', 'read'), ('WRITE', 'write')], default='write', max_length=8),
        ),
    ]
