# Generated by Django 5.1.7 on 2025-04-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0007_remove_invitation_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='permission',
            field=models.CharField(choices=[('READ', 'read'), ('WRITE', 'write')], default='write', max_length=8),
        ),
    ]
