# Generated by Django 5.1.5 on 2025-02-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_file_name_alter_file_file_alter_folder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subfolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
