# Generated by Django 5.1.5 on 2025-02-22 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_subfolder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subfolder',
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='cloud.folder'),
        ),
    ]
